import { FileItem, DriveInfo, IndexedLocation } from '../types';

export function createDefaultHighwaySampleFiles(): {
  files: FileItem[];
  drives: DriveInfo[];
  locations: IndexedLocation[];
} {
  const rootPath = 'D:\\NH48_Highway_Project';
  const now = new Date('2026-09-28T09:00:00Z').toISOString();
  const yesterday = new Date('2026-09-27T14:30:00Z').toISOString();
  const lastWeek = new Date('2026-09-20T10:15:00Z').toISOString();
  const lastMonth = new Date('2026-08-15T11:00:00Z').toISOString();

  const files: FileItem[] = [
    // Folders in D: drive
    {
      id: 'folder-root',
      name: 'NH48_Highway_Project',
      extension: '',
      path: rootPath,
      parentPath: 'D:',
      category: 'folder',
      size: 0,
      createdDate: lastMonth,
      modifiedDate: now,
      isFolder: true,
      itemCount: 9,
      isLocalImported: true,
    },
    {
      id: 'folder-archive',
      name: '00_Project_Archive_Backup',
      extension: '',
      path: 'D:\\00_Project_Archive_Backup',
      parentPath: 'D:',
      category: 'folder',
      size: 0,
      createdDate: lastMonth,
      modifiedDate: lastWeek,
      isFolder: true,
      itemCount: 3,
      isLocalImported: true,
    },
    {
      id: 'file-drive-readme',
      name: 'NH48_Engineering_Drive_Readme.txt',
      extension: 'txt',
      path: 'D:\\NH48_Engineering_Drive_Readme.txt',
      parentPath: 'D:',
      category: 'other',
      size: 2450,
      createdDate: lastMonth,
      modifiedDate: yesterday,
      isFolder: false,
      tags: ['Approved'],
      contentSnippet: 'InfraFinder Project Drive Directory: NH-48 6-Laning Engineering Workspace Index.',
      contentFull: `========================================================================
INFRAFINDER HIGHWAY PROJECT WORKSPACE DIRECTORY
PROJECT: NH-48 6-Laning Expansion & Upgrade (Km 42+000 to Km 150+000)
AUTHORITY: National Highways Authority of India (NHAI)
CONCESSIONAIRE: InfraCorp Highway Developers Ltd.
========================================================================
Directories included:
1. 01_Billing_and_IPC - Monthly IPC, RA Bills, BOQ Rate Analysis
2. 02_CAD_Drawings - AutoCAD GAD, Plan, TCS, Structure Cross-Sections
3. 03_Quality_and_Safety - Concrete Cube Test Logs, Safety Audits, DPRs
4. 04_Contracts_and_MoRTH_Specs - Concession Agreement, MoRTH Specifications
========================================================================`,
      isLocalImported: true,
    },

    // Subfolders inside NH48_Highway_Project
    {
      id: 'folder-billing',
      name: '01_Billing_and_IPC',
      extension: '',
      path: `${rootPath}\\01_Billing_and_IPC`,
      parentPath: rootPath,
      category: 'folder',
      size: 0,
      createdDate: lastMonth,
      modifiedDate: yesterday,
      isFolder: true,
      itemCount: 5,
      isLocalImported: true,
    },
    {
      id: 'folder-drawings',
      name: '02_CAD_Drawings',
      extension: '',
      path: `${rootPath}\\02_CAD_Drawings`,
      parentPath: rootPath,
      category: 'folder',
      size: 0,
      createdDate: lastMonth,
      modifiedDate: lastWeek,
      isFolder: true,
      itemCount: 6,
      isLocalImported: true,
    },
    {
      id: 'folder-quality',
      name: '03_Quality_and_Safety',
      extension: '',
      path: `${rootPath}\\03_Quality_and_Safety`,
      parentPath: rootPath,
      category: 'folder',
      size: 0,
      createdDate: lastMonth,
      modifiedDate: now,
      isFolder: true,
      itemCount: 4,
      isLocalImported: true,
    },
    {
      id: 'folder-contracts',
      name: '04_Contracts_and_MoRTH_Specs',
      extension: '',
      path: `${rootPath}\\04_Contracts_and_MoRTH_Specs`,
      parentPath: rootPath,
      category: 'folder',
      size: 0,
      createdDate: lastMonth,
      modifiedDate: lastMonth,
      isFolder: true,
      itemCount: 2,
      isLocalImported: true,
    },

    // Files directly in the root project folder (D:\NH48_Highway_Project)
    {
      id: 'file-overview-pdf',
      name: 'Executive_Project_Overview_and_Alignment_Index.pdf',
      extension: 'pdf',
      path: `${rootPath}\\Executive_Project_Overview_and_Alignment_Index.pdf`,
      parentPath: rootPath,
      category: 'pdf',
      size: 8940000,
      createdDate: lastMonth,
      modifiedDate: now,
      isFolder: false,
      tags: ['Approved', 'Urgent'],
      metadata: { Chainage: 'KM 42+000 to KM 150+000', Package: 'PKG-01 & PKG-02' },
      contentSnippet: 'Executive Project Overview for 6-laning of NH-48 corridor with detailed key alignment map, interchange locations, and milestone progress summary.',
      contentFull: 'Executive Project Overview for 6-laning of NH-48 corridor with key alignment map, interchange locations, bypass chainages, and milestone progress summary verified by Independent Engineer and NHAI Project Director.',
      isLocalImported: true,
    },
    {
      id: 'file-master-schedule',
      name: 'Master_Construction_Schedule_and_Milestones.xlsx',
      extension: 'xlsx',
      path: `${rootPath}\\Master_Construction_Schedule_and_Milestones.xlsx`,
      parentPath: rootPath,
      category: 'excel',
      size: 3450000,
      createdDate: lastMonth,
      modifiedDate: yesterday,
      isFolder: false,
      tags: ['Approved'],
      metadata: { Period: 'FY 2026-2027', Package: 'PKG-ALL' },
      contentSnippet: 'Integrated master baseline construction schedule showing critical path activities, earthwork progress, and flyover completion dates.',
      contentFull: 'Integrated master baseline construction schedule showing critical path activities, earthwork progress, major bridge milestones, and flyover completion dates under EPC contract terms.',
      isLocalImported: true,
    },
    {
      id: 'file-key-plan-cad',
      name: 'NH48_General_Alignment_Key_Map_TCS.dwg',
      extension: 'dwg',
      path: `${rootPath}\\NH48_General_Alignment_Key_Map_TCS.dwg`,
      parentPath: rootPath,
      category: 'cad',
      size: 24500000,
      createdDate: lastMonth,
      modifiedDate: lastWeek,
      isFolder: false,
      tags: ['Approved', 'MoRTH-Compliant'],
      metadata: { Chainage: 'KM 42+000 to KM 150+000', Scale: '1:5000' },
      contentSnippet: 'AutoCAD General Alignment Key Map with Typical Cross Section (TCS) schedules.',
      contentFull: 'AutoCAD General Alignment Key Map with Typical Cross Section (TCS) schedules, right-of-way demarcation lines, toll plaza layout, and service road details.',
      isLocalImported: true,
    },
    {
      id: 'file-epc-contract',
      name: 'Concessionaire_EPC_Agreement_Contract.pdf',
      extension: 'pdf',
      path: `${rootPath}\\Concessionaire_EPC_Agreement_Contract.pdf`,
      parentPath: rootPath,
      category: 'pdf',
      size: 16800000,
      createdDate: lastMonth,
      modifiedDate: lastMonth,
      isFolder: false,
      tags: ['Approved'],
      metadata: { ContractNo: 'NHAI/EPC/2025/NH48/01' },
      contentSnippet: 'Engineering Procurement and Construction (EPC) standard contract agreement with Schedule B, C, D, H milestones.',
      contentFull: 'Engineering Procurement and Construction (EPC) standard contract agreement between National Highways Authority of India and Concessionaire with Schedule B (Scope of Work), Schedule C (Project Facilities), and Schedule H (Contract Price Weightages).',
      isLocalImported: true,
    },
    {
      id: 'file-team-directory',
      name: 'Site_Management_Team_Contact_Directory.docx',
      extension: 'docx',
      path: `${rootPath}\\Site_Management_Team_Contact_Directory.docx`,
      parentPath: rootPath,
      category: 'word',
      size: 1250000,
      createdDate: lastMonth,
      modifiedDate: yesterday,
      isFolder: false,
      tags: ['In Review'],
      contentSnippet: 'Field engineering officers, safety managers, laboratory heads, and Independent Engineer contact directory.',
      contentFull: 'Field engineering officers, structural resident engineers, road safety managers, material testing laboratory heads, and Independent Engineer key personnel contact directory for NH-48 site office.',
      isLocalImported: true,
    },

    // Files in 04_Contracts_and_MoRTH_Specs
    {
      id: 'file-morth-spec',
      name: 'MoRTH_5th_Revision_Specifications_Roads_Bridges.pdf',
      extension: 'pdf',
      path: `${rootPath}\\04_Contracts_and_MoRTH_Specs\\MoRTH_5th_Revision_Specifications_Roads_Bridges.pdf`,
      parentPath: `${rootPath}\\04_Contracts_and_MoRTH_Specs`,
      category: 'pdf',
      size: 28500000,
      createdDate: lastMonth,
      modifiedDate: lastMonth,
      isFolder: false,
      tags: ['Approved', 'MoRTH-Compliant'],
      contentSnippet: 'Ministry of Road Transport and Highways (MoRTH) Specifications for Road and Bridge Works (Fifth Revision).',
      contentFull: 'Ministry of Road Transport and Highways (MoRTH) Specifications for Road and Bridge Works (Fifth Revision) covering Section 300 (Earthwork), Section 400 (Sub-bases and Bases), Section 500 (Bituminous Pavements), and Section 1500-2200 (Concrete and Structural Works).',
      isLocalImported: true,
    },
    {
      id: 'file-irc-sp84',
      name: 'IRC_SP_84_Manual_of_Specifications_Standards.pdf',
      extension: 'pdf',
      path: `${rootPath}\\04_Contracts_and_MoRTH_Specs\\IRC_SP_84_Manual_of_Specifications_Standards.pdf`,
      parentPath: `${rootPath}\\04_Contracts_and_MoRTH_Specs`,
      category: 'pdf',
      size: 19200000,
      createdDate: lastMonth,
      modifiedDate: lastMonth,
      isFolder: false,
      tags: ['Approved'],
      contentSnippet: 'IRC:SP:84 Manual of Specifications and Standards for Four Laning of Highways.',
      contentFull: 'Indian Roads Congress IRC:SP:84 Manual of Specifications and Standards for Four Laning / Six Laning of Highways through Public Private Partnership.',
      isLocalImported: true,
    },

    // Files in root folder
    {
      id: 'file-ipc24',
      name: 'IPC_24_Interim_Payment_Certificate_Summary.xlsx',
      extension: 'xlsx',
      path: `${rootPath}\\01_Billing_and_IPC\\IPC_24_Interim_Payment_Certificate_Summary.xlsx`,
      parentPath: `${rootPath}\\01_Billing_and_IPC`,
      category: 'excel',
      size: 2845000,
      createdDate: lastWeek,
      modifiedDate: yesterday,
      isFolder: false,
      tags: ['Approved', 'Billing'],
      metadata: { Chainage: 'KM 42+000 to KM 86+500', Package: 'PKG-02' },
      contentSnippet: 'Interim Payment Certificate IPC-24 verified against site measurement sheets for earthwork and bituminous pavement.',
      contentFull: 'Interim Payment Certificate IPC-24 verified against site measurement sheets for earthwork, WMM sub-base and DBM bituminous pavement layers. Total certified amount INR 42.85 Cr approved by Independent Engineer.',
      isLocalImported: true,
    },
    {
      id: 'file-ra18',
      name: 'RA_Bill_18_Quantity_Measurement_Book.xlsx',
      extension: 'xlsx',
      path: `${rootPath}\\01_Billing_and_IPC\\RA_Bill_18_Quantity_Measurement_Book.xlsx`,
      parentPath: `${rootPath}\\01_Billing_and_IPC`,
      category: 'excel',
      size: 4210000,
      createdDate: lastMonth,
      modifiedDate: lastWeek,
      isFolder: false,
      tags: ['Approved'],
      metadata: { Chainage: 'KM 60+200', Item: 'Culvert Box' },
      contentSnippet: 'Running Account Bill RA-18 itemized bill of quantities with reinforcement steel cross-verification.',
      contentFull: 'Running Account Bill RA-18 itemized bill of quantities with reinforcement steel cross-verification and structural concrete pouring logs approved.',
      isLocalImported: true,
    },
    {
      id: 'file-boq',
      name: 'BOQ_Schedule_B_Price_Escalation_Indices.xlsx',
      extension: 'xlsx',
      path: `${rootPath}\\01_Billing_and_IPC\\BOQ_Schedule_B_Price_Escalation_Indices.xlsx`,
      parentPath: `${rootPath}\\01_Billing_and_IPC`,
      category: 'excel',
      size: 1540000,
      createdDate: lastMonth,
      modifiedDate: now,
      isFolder: false,
      tags: ['Draft'],
      metadata: { Revision: 'Rev-04' },
      contentSnippet: 'Wholesale price index escalation calculation for diesel, cement, bitumen and labor components.',
      contentFull: 'Wholesale price index escalation calculation for diesel, cement, bitumen and labor components under clause 10CC of EPC agreement draft.',
      isLocalImported: true,
    },
    {
      id: 'file-bridge-cad-reva',
      name: 'Ch_124_Flyover_Superstructure_CrossSection_revA.dwg',
      extension: 'dwg',
      path: `${rootPath}\\02_CAD_Drawings\\Ch_124_Flyover_Superstructure_CrossSection_revA.dwg`,
      parentPath: `${rootPath}\\02_CAD_Drawings`,
      category: 'cad',
      size: 17200000,
      createdDate: lastMonth,
      modifiedDate: '2026-08-20T10:00:00Z',
      isFolder: false,
      tags: ['Draft'],
      metadata: { Chainage: 'KM 124+450', Revision: 'Rev-A', Status: 'Superseded' },
      contentSnippet: 'Initial structural cross-section draft with preliminary girder spacing.',
      contentFull: 'Initial structural cross-section draft for 3 x 35m PSC Box Girder with preliminary prestressing tendon estimates prior to Independent Engineer review comments.',
      isLocalImported: true,
    },
    {
      id: 'file-bridge-cad-revb',
      name: 'Ch_124_Flyover_Superstructure_CrossSection_revB.dwg',
      extension: 'dwg',
      path: `${rootPath}\\02_CAD_Drawings\\Ch_124_Flyover_Superstructure_CrossSection_revB.dwg`,
      parentPath: `${rootPath}\\02_CAD_Drawings`,
      category: 'cad',
      size: 17900000,
      createdDate: lastMonth,
      modifiedDate: '2026-09-05T14:30:00Z',
      isFolder: false,
      tags: ['In Review'],
      metadata: { Chainage: 'KM 124+450', Revision: 'Rev-B', Status: 'Superseded' },
      contentSnippet: 'Revised pier cap reinforcement layout incorporating crash barrier load revisions.',
      contentFull: 'Revised structural cross-section addressing pier cap torsional shear reinforcement and seismic restrainer clearances per IRC:112 guidelines.',
      isLocalImported: true,
    },
    {
      id: 'file-bridge-cad-final',
      name: 'Ch_124_Flyover_Superstructure_CrossSection_final.dwg',
      extension: 'dwg',
      path: `${rootPath}\\02_CAD_Drawings\\Ch_124_Flyover_Superstructure_CrossSection_final.dwg`,
      parentPath: `${rootPath}\\02_CAD_Drawings`,
      category: 'cad',
      size: 18450000,
      createdDate: lastMonth,
      modifiedDate: lastWeek,
      isFolder: false,
      tags: ['Approved', 'MoRTH-Compliant'],
      metadata: { Chainage: 'KM 124+450', Span: '3 x 35m PSC Box Girder', Revision: 'Final Approved' },
      contentSnippet: 'Final Good for Construction (GFC) AutoCAD GAD structural cross-section with prestressing tendon profile details.',
      contentFull: 'Final Good for Construction (GFC) AutoCAD GAD structural cross-section with prestressing tendon profile details, pier cap reinforcement, and elastomeric bearing design per IRC:112 and MoRTH Specifications.',
      isLocalImported: true,
    },
    {
      id: 'file-alignment-cad-v1',
      name: 'Main_Carriageway_Horizontal_Alignment_Plan_v1.dxf',
      extension: 'dxf',
      path: `${rootPath}\\02_CAD_Drawings\\Main_Carriageway_Horizontal_Alignment_Plan_v1.dxf`,
      parentPath: `${rootPath}\\02_CAD_Drawings`,
      category: 'cad',
      size: 11400000,
      createdDate: lastMonth,
      modifiedDate: '2026-09-10T12:00:00Z',
      isFolder: false,
      tags: ['Draft'],
      metadata: { Chainage: 'KM 0+000 to KM 45+000', Revision: 'v1', Status: 'Superseded' },
      contentSnippet: 'Preliminary horizontal alignment baseline with standard 600m minimum curve radius.',
      contentFull: 'Preliminary horizontal alignment baseline prepared in Civil 3D before utility conflict survey.',
      isLocalImported: true,
    },
    {
      id: 'file-alignment-cad-v2',
      name: 'Main_Carriageway_Horizontal_Alignment_Plan_v2.dxf',
      extension: 'dxf',
      path: `${rootPath}\\02_CAD_Drawings\\Main_Carriageway_Horizontal_Alignment_Plan_v2.dxf`,
      parentPath: `${rootPath}\\02_CAD_Drawings`,
      category: 'cad',
      size: 12100000,
      createdDate: lastMonth,
      modifiedDate: yesterday,
      isFolder: false,
      tags: ['Approved'],
      metadata: { Chainage: 'KM 0+000 to KM 45+000', Revision: 'v2' },
      contentSnippet: 'Updated horizontal curve radius, transition spirals, and super-elevation runoff diagram.',
      contentFull: 'Updated horizontal curve radius, transition spirals, and super-elevation runoff diagram prepared in AutoCAD Civil 3D for 6-lane configuration.',
      isLocalImported: true,
    },
    {
      id: 'file-culvert-reva',
      name: 'Culvert_Hydraulic_Calculation_Ch60_revA.xlsx',
      extension: 'xlsx',
      path: `${rootPath}\\01_Billing_and_IPC\\Culvert_Hydraulic_Calculation_Ch60_revA.xlsx`,
      parentPath: `${rootPath}\\01_Billing_and_IPC`,
      category: 'excel',
      size: 1820000,
      createdDate: lastMonth,
      modifiedDate: '2026-09-08T09:00:00Z',
      isFolder: false,
      tags: ['Draft'],
      metadata: { Chainage: 'KM 60+200', Revision: 'Rev-A', Status: 'Superseded' },
      contentSnippet: 'Catchment runoff discharge estimation using Rational Formula.',
      contentFull: 'Catchment runoff discharge estimation using Rational Formula with 50-year return period rainfall intensity.',
      isLocalImported: true,
    },
    {
      id: 'file-culvert-final',
      name: 'Culvert_Hydraulic_Calculation_Ch60_final.xlsx',
      extension: 'xlsx',
      path: `${rootPath}\\01_Billing_and_IPC\\Culvert_Hydraulic_Calculation_Ch60_final.xlsx`,
      parentPath: `${rootPath}\\01_Billing_and_IPC`,
      category: 'excel',
      size: 2150000,
      createdDate: lastMonth,
      modifiedDate: yesterday,
      isFolder: false,
      tags: ['Approved'],
      metadata: { Chainage: 'KM 60+200', Revision: 'Final', Item: 'Box Culvert 2x2m' },
      contentSnippet: 'Final approved hydraulic afflux and scour depth calculations verified by Independent Engineer.',
      contentFull: 'Final approved hydraulic afflux and scour depth calculations verified by Independent Engineer conforming to IRC:SP:13 and MoRTH guidelines.',
      isLocalImported: true,
    },
    {
      id: 'file-dpr',
      name: 'DPR_Volume_IV_Environmental_and_Forest_Clearance.pdf',
      extension: 'pdf',
      path: `${rootPath}\\03_Quality_and_Safety\\DPR_Volume_IV_Environmental_and_Forest_Clearance.pdf`,
      parentPath: `${rootPath}\\03_Quality_and_Safety`,
      category: 'pdf',
      size: 14600000,
      createdDate: lastMonth,
      modifiedDate: now,
      isFolder: false,
      tags: ['Urgent', 'In Review'],
      metadata: { Status: 'MoEFCC Stage-II Pending' },
      contentSnippet: 'Detailed Project Report Environmental Impact Assessment with wildlife corridor mitigation measures.',
      contentFull: 'Detailed Project Report Environmental Impact Assessment with wildlife corridor mitigation measures, compensatory afforestation scheme, and tree felling permissions along NH-48 right-of-way.',
      isLocalImported: true,
    },
    {
      id: 'file-audit-log',
      name: 'Safety_Audit_Field_Observations_Ch85.log',
      extension: 'log',
      path: `${rootPath}\\03_Quality_and_Safety\\Safety_Audit_Field_Observations_Ch85.log`,
      parentPath: `${rootPath}\\03_Quality_and_Safety`,
      category: 'other',
      size: 38400,
      createdDate: yesterday,
      modifiedDate: now,
      isFolder: false,
      tags: ['Urgent', 'Draft'],
      metadata: { Chainage: 'KM 85+600', Inspector: 'Road Safety Auditor' },
      contentSnippet: '[CRITICAL_WARN] Traffic diversion signage missing retroreflective retro-tape at median crossover.',
      contentFull: `[2026-09-28 08:30:15] [INFO] Road safety audit initiated at Chainage KM 85+200.
[2026-09-28 08:42:01] [WARNING] Speed calming rumble strips missing 200m advance warning board.
[2026-09-28 09:15:33] [CRITICAL_WARN] Traffic diversion signage missing retroreflective retro-tape at median crossover Ch 85+600.
[2026-09-28 09:45:00] [ACTION_REQUIRED] Contractor instructed to rectify solar blinkers and hazard crash cushions immediately.
[2026-09-28 10:12:00] [STATUS] Inspection logged for urgent rectification.`,
      isLocalImported: true,
    },
    {
      id: 'file-mpr',
      name: 'Contractor_Monthly_Progress_Report_Aug.docx',
      extension: 'docx',
      path: `${rootPath}\\03_Quality_and_Safety\\Contractor_Monthly_Progress_Report_Aug.docx`,
      parentPath: `${rootPath}\\03_Quality_and_Safety`,
      category: 'word',
      size: 5120000,
      createdDate: lastMonth,
      modifiedDate: lastWeek,
      isFolder: false,
      tags: ['In Review'],
      metadata: { Period: 'August 2026', Progress: '68.4% Cumulative' },
      contentSnippet: 'Physical and financial cumulative progress against master construction baseline program.',
      contentFull: 'Physical progress achieved 68.4% against target 72.1%. Major variance due to monsoon delays at major bridge over river Sabarmati. Revised recovery program submitted to Independent Engineer.',
      isLocalImported: true,
    },
  ];

  const drives: DriveInfo[] = [
    {
      letter: 'D:',
      label: 'Highway Project Drive (D:)',
      totalBytes: 2 * 1024 * 1024 * 1024 * 1024, // 2 TB
      usedBytes: 58800000,
      type: 'Engineering Drive',
    },
  ];

  const locations: IndexedLocation[] = [
    {
      id: 'loc-nh48-default',
      path: rootPath,
      name: 'NH48_Highway_Project',
      drive: 'D:',
      fileCount: files.length,
      isIncluded: true,
    },
  ];

  return { files, drives, locations };
}
